/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f1xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void USART1Init();
void ClockInit();
void USART1_sendByte(uint8_t byte);

int main(void)
{
	ClockInit();
	USART1Init();

    /* Loop forever */
	for(;;);
}

void ClockInit(){
	// Bit 4 PRFTBE: Prefetch buffer enable
	FLASH->ACR |= (1 << 4); // Prefetch is enabled

	//
	// HSE Configuration
	// Bit 16 HSEON: HSE clock enable
	RCC->CR |= (1 << 16); // HSE oscillator ON

	/* Wait till HSE is ready */
	// Bit 17 HSERDY: External high-speed clock ready flag
	while(!(RCC->CR & (1 << 17)));

	//
	// PLL Configuration
	/* Disable the main PLL. */
	// Bit 24 PLLON: PLL enable
	RCC->CR &= ~(1 << 24); // PLL OFF

	/* Wait till PLL is disabled */
	// Bit 25 PLLRDY: PLL clock ready flag
	while(RCC->CR & (1 << 25));

	/* Set PREDIV1 Value */
	// Bit 17 PLLXTPRE: HSE divider for PLL entry
	RCC->CFGR &= ~(1 << 17); // HSE clock not divided

	/* Configure the main PLL clock source and multiplication factors. */
	// Bit 16 PLLSRC: PLL entry clock source
	RCC->CFGR |= (1 << 16); // HSE oscillator clock selected as PLL input clock
	// Bits 21:18 PLLMUL: PLL multiplication factor
	RCC->CFGR &= ~(0b1111 << 18);
	RCC->CFGR |= (0b111 << 18); // PLL input clock x 9

	/* Enable the main PLL. */
	// Bit 24 PLLON: PLL enable
	RCC->CR |= (1 << 24); // PLL ON

	/* Wait till PLL is ready */
	// Bit 25 PLLRDY: PLL clock ready flag
	while(!(RCC->CR & (1 << 25)));

	// Bits 2:0 LATENCY: Latency
	FLASH->ACR &= (0b111 << 0);
	FLASH->ACR |= (0b10 << 0); // Two wait states, if 48 MHz < SYSCLK <= 72 MHz

	// HCLK Configuration
	/* Set the highest APBx dividers in order to ensure that we do not go through
	      5     a non-spec phase whatever we decrease or increase HCLK. */
	// Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
	RCC->CFGR |= (0b111 << 8); // HCLK divided by 16
	// Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
	RCC->CFGR |= (0b111 << 11); // HCLK divided by 16

	/* Set the new HCLK clock divider */
	// Bits 7:4 HPRE: AHB prescaler
	RCC->CFGR &= ~(0b1111 << 4); // SYSCLK not divided

	//
	// SYSCLK Configuration
	/* PLL is selected as System Clock Source */
	// Bit 25 PLLRDY: PLL clock ready flag
	/* Check the PLL ready flag */
	while(!(RCC->CR & (1 << 25)));

	// Bits 1:0 SW: System clock switch
	RCC->CFGR &= ~(1 << 0); // PLL selected as system clock
	RCC->CFGR |= (1 << 1);

	while( ( ( RCC->CFGR & (0b11 << 2) ) >> 2 ) != (0b10) ); // Bits 3:2 SWS: System clock switch status

	//
	// PCLK1 Configuration
	// Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
	RCC->CFGR &= ~(0b111 << 8);
	RCC->CFGR |= (0b100 << 8); // HCLK divided by 2

	// PCLK2 Configuration
	// Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
	RCC->CFGR &= ~(0b111 << 11); // HCLK not divided
}

void USART1Init()
{
	// Bit 0 AFIOEN: Alternate function IO clock enable
	// Bit 3 IOPBEN: IO port B clock enable
	// Bit 14 USART1EN: USART1 clock enable
	RCC->APB2ENR |= (1 << 0) | (1 << 3) | (1 << 14);

	//
	// Clear bit of PB16 and PB17
	GPIOB->CRL &= ~(0xff << 24);

	// Output mode, max speed 50 MHz.
	// Input mode (reset state)
	GPIOB->CRL |= (0b11 << 24) | (0b00 << 28);

	// Alternate function output Push-pull
	// Floating input (reset state)
	GPIOB->CRL |= (0b10 << 26) | (0b01 << 30);

	//
	// Bit 2 USART1_REMAP: USART1 remapping
	AFIO->MAPR |= (1 << 2); // Remap (TX/PB6, RX/PB7)

	//
	// Bit 13 UE: USART enable
	USART1->CR1 &= ~(1 << 13); // USART prescaler and outputs disabled

	//
	/*-------------------------- USART CR2 Configuration -----------------------*/
	/* Configure the UART Stop Bits: Set STOP[13:12] bits
		     according to huart->Init.StopBits value */
	// Bits 13:12 STOP: STOP bits
	USART1->CR2 &= ~(0b11 << 12); // 1 Stop bit

	//
	/*-------------------------- USART CR1 Configuration -----------------------*/
	/* Configure the UART Word Length, Parity and mode:
		     Set the M bits
		     Set PCE and PS bits
		     Set TE and RE bits*/
	// Bit 12 M: Word length
	// Bit 10 PCE: Parity control enable
	// Bit 9 PS: Parity selection
	USART1->CR1 &= ~((1 << 12) | (1 << 10) | (1 << 9));

	// Bit 2 RE: Receiver enable
	// Bit 3 TE: Transmitter enable
	USART1->CR1 |= (1 << 2) | (1 << 3);

	//
	/*-------------------------- USART CR3 Configuration -----------------------*/
	/* Configure the UART HFC: Set CTSE and RTSE bits according to huart->Init.HwFlowCtl value */
	// Bit 8 RTSE: RTS enable
	// Bit 9 CTSE: CTS enable
	USART1->CR3 &= ~((1 << 8) | (1 << 9));

	/*-------------------------- USART BRR Configuration ---------------------*/
	USART1->BRR = 625; // 72M/115200 = 625

	/* In asynchronous mode, the following bits must be kept cleared:
		     - LINEN and CLKEN bits in the USART_CR2 register,
		     - SCEN, HDSEL and IREN  bits in the USART_CR3 register.*/
	// Bit 11 CLKEN: Clock enable
	// Bit 14 LINEN: LIN mode enable
	USART1->CR2 &= ~((1 << 11) | (1 << 14));

	// Bit 1 IREN: IrDA mode enable
	// Bit 3 HDSEL: Half-duplex selection
	// Bit 5 SCEN: Smartcard mode enable
	USART1->CR3 &= ~((1 << 1) | (1 << 3) | (1 << 5));

	//
	/* Enable the UART Error Interrupt: (Frame error, noise error, overrun error) */
	// Bit 0 EIE: Error interrupt enable
	USART1->CR3 |= (1 << 0); // An interrupt is generated whenever DMAR=1 in the USART_CR3 register and FE=1 or ORE=1 or NE=1 in the USART_SR register.

	/* Enable the UART Data Register not empty Interrupt */
	// Bit 5 RXNEIE: RXNE interrupt enable
	USART1->CR1 |= (1 << 5); // A USART interrupt is generated whenever ORE=1 or RXNE=1 in the USART_SR register

	/* USART1 interrupt Init */
	NVIC_SetPriority(USART1_IRQn, 0);
	NVIC_EnableIRQ(USART1_IRQn);

	//
	// Bit 13 UE: USART enable
	USART1->CR1 |= (1 << 13); // USART enabled
}

void USART1_IRQHandler()
{
	uint8_t c = USART1->DR;

	USART1_sendByte(c);
}
void USART1_sendByte(uint8_t byte){
	USART1->DR = byte;

	// Bit 6 TC: Transmission complete
	while(!(USART1->SR & (1 << 6)));
	USART1->SR &= ~(1<<6); // clear TC flag
}
